# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d947bd42b6d502bf49bf198e84161b3c00b524cb72def6f94dc87420986172aca039e19b3e27ae61850b22b41b311aed8b6c908d5e24a5c667c131085ac20a4

test:
  secret_key_base: 941212c5f622c79260e3b85f7b386b79f342ffcd249a6c0ca0e87c83c6784b6840a907910acf277d855c0bc9e734a1be0ba9dd276f0103aebdd8ebb2bc019c4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
